WawaStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WawaStore.Models;

namespace WawaStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

WawaStore/Components/NavigationMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WawaStore.Models;

namespace WawaStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;

        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x));
        }
    }
}

WawaStore/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WawaStore.Models;
using WawaStore.Models.ViewModels;

namespace WawaStore.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;

        private Cart cart;

        public CartController(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int productId,
        string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

WawaStore/Views/Shared/ProductSummary.cshtml
@model Product 
  <div class="col">
    <div class="card h-100">
         <img src="@Model.Images" class="card-img-top" alt="...">
      <div class="card-body">
        <h3 class="card-title">
            <strong>@Model.Name</strong>
        </h3>
        <p class="card-text lead">
            @Model.Description
        </p>
         <div class="card-footer">
      
        <span class="float-left bg-success text-white rounded m-2 p-1"> 
            @Model.Price.ToString("c") 
        </span> 

       <form id="@Model.ProductID" asp-action="AddToCart" asp-controller="Cart" method="post" class="float-right m-2 p-1"> 
            <input type="hidden" asp-for="ProductID" /> 
            <input type="hidden" name="returnUrl" 
                    value="@ViewContext.HttpContext.Request.PathAndQuery()" /> 
            <button type="submit" class="btn btn-danger btn-sm float-right" style="background-color:#dc3545;"> 
                Add To Cart 
           </button> 
       </form>  
       </div>
    </div>
  </div>
 </div>

WawaStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html> 
<html> 
<head> 
    <meta name="viewport" content="width=device-width" /> 
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" /> 
    <title>@ViewBag.Title</title> 
    <style> 
        .input-validation-error { 
            border-color: red; 
            background-color: #fee; 
        } 
    </style> 
    <script asp-src-include="lib/jquery/**/jquery.min.js"></script> 
    <script asp-src-include="lib/jquery-validation/**/jquery.validate.min.js"></script> 
    <script asp-src-include="lib/jquery-validation-unobtrusive/**/*.min.js"></script> 
 
</head> 
<body> 
    <div class="container">
         <div class="card"> 
            <div class="card-header"> 
                <h4>@ViewBag.Title</h4> 
            </div> 
            <div class="card-body"> 
                @if (TempData["message"] != null) 
                { 
                    <div class="alert alert-success">@TempData["message"]</div> 
                } 
 
                @RenderBody() 
            </div> 
        </div> 
    </div> 
</body> 
</html> 

WawaStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" /> 

    <link rel="stylesheet" asp-href-include="lib/font-awesome/css/*.css" /> 
    <title>WawaStore</title>
</head>
<body>
    <nav class="navbar navbar-light justify-content-between" style="background-color:floralwhite">   
         <a class="navbar-brand" href="#"> 
              <img src="https://cdn.shopify.com/s/files/1/0833/8827/files/MainLogo_Wawa_150x.png?v=1615992700" alt="" width="120" height="60">  
             </a>

         <div class="float-right"> 
            @await Component.InvokeAsync("CartSummary") 
        </div> 
    </nav> 


    <div class="container"> 
        <div class="row"> 
            <div class="col col-md-3"> 
                @await Component.InvokeAsync("NavigationMenu")  
            </div> 
            <div class="col col-md-9"> 
    
        @RenderBody()
    </div>
    </div> 
    </div> 
</body>
</html>